### ISSUE TITLE
Morris method input

### ISSUE THREAD

**Issue by vijaya65** [SciML/DiffEqSensitivity.jl#215]
I have a question regarding the Morris method in the  differential equation package.
The documentation does not describe how the number of trajectories is calculated for the Morris method.
In the example given for the LotkaVolterra model with 4 parameters, an unusually large number of trajectories
is included in the input

m = gsa(f1,Morris(total _num_trajectory=1000,num_trajectory=150),[[1,5],[1,5],[1,5],[1,5]])

From what I have read about the method for 4 parameters the number of trajectories would be 5x(r=8) or 40 trajectories at most. 
Do you know how the numbers 1000 and 150 are calculated for the Lotka Volterra model and what they represent?
(I opened as a new issue as an old issue with similar title was closed)

**Comment by Vaibhavdixit02** [comment]
Was fixed by https://github.com/SciML/DiffEqSensitivity.jl/pull/216
