### ISSUE TITLE
RegressionGSA parameter matrix dimensions

### ISSUE THREAD

**Issue by MFairley** [SciML/DiffEqSensitivity.jl#232]
The docs state that " If batch=true, then f takes in a matrix where each row is a set of parameters, and returns a matrix where each row is a the output for the corresponding row of parameters."

However, it seems that RegressionGSA generates an X matrix with a column as a set of parameters.

`_y = [f(X[:, j]) for j in axes(X, 2)]`

This leads to a problem when a user implements f for batch gsa and is expecting each row to be a parameter set according to the docs and the example at the end of the gas docs.

**Comment by ChrisRackauckas** [comment]
Oh yes that's a problem. Should just have an easy fix by transposing it. @Vaibhavdixit02 do you got this? Otherwise I'll try and find time over the weekend.

**Comment by Vaibhavdixit02** [comment]
I got this 👍

**Comment by Vaibhavdixit02** [comment]
The snippet posted is from the branch that goes into `batch=false` so this is not really an issue, @MFairley can you show what code gave you error?

**Comment by MFairley** [comment]
That line just shows the shape of X. The same X goes into `_y=f(X)` where `f` is the user supplied function when batch=true. The user expects each row to be a set of parameters.

**Comment by Vaibhavdixit02** [comment]
Apologies for the brain fart, you are correct. I have updated the docs and the examples to show the correct usage https://github.com/SciML/DiffEqDocs.jl/pull/355
