### ISSUE TITLE
Gradients double if connection to `p` is explicit?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqSensitivity.jl#271]
```julia
using Flux, DiffEqFlux, DifferentialEquations

#parameter
p=[5.0f0]
#ini state
u0=[2.0f0]

function f(u,p,t)
   p[1]*u
end

dt=0.005f0
tspan = (0.0,dt)

function dynamics1(p)
   prob1 = ODEProblem(f,u0,tspan,p)
   solve(prob1,Heun(), dt=dt,saveat=[dt],adaptive=false)[1,:]
end

prob2 = ODEProblem(f,u0,tspan,p)
function dynamics2(p)
   solve(prob2,Heun(),dt=dt,saveat=[dt],adaptive=false)[1,:]
end

function dynamics3(p)
   solve(prob2,Heun(),p=p,dt=dt,saveat=[dt],adaptive=false)[1,:]
end

function dynamics4()
   solve(prob2,Heun(),dt=dt,saveat=[dt],adaptive=false)[1,:]
end

#some loss function
loss1(p) = sum(abs.(dynamics1(p)-u0))
loss2(p) = sum(abs.(dynamics2(p)-u0))
loss3(p) = sum(abs.(dynamics3(p)-u0))
loss4() = sum(abs.(dynamics4()-u0))

θ = Flux.params(p)
gs1 = gradient(θ) do
   loss1(p)
end

gs2 = gradient(θ) do
   loss2(p)
end

gs3 = gradient(θ) do
   loss3(p)
end

gs4 = gradient(θ) do
   loss4()
end

#gs1 exactly twice larger as the other version
println("grads 1:", gs1[p] ) #Float32[0.020503124]
println("grads 2:", gs2[p] ) #Float32[0.010251562]
println("grads 3:", gs3[p] ) #Float32[0.020503124]
println("grads 4:", gs4[p] ) #Float32[0.010251562]

using ForwardDiff
ForwardDiff.gradient(loss1,p) # Float32[0.010249999]
```

**Comment by ChrisRackauckas** [comment]
@dhairyagandhi96

**Comment by dhairyagandhi96** [comment]
Might be relevant https://discourse.julialang.org/t/why-calculating-gradients-from-params-is-different-than-doing-it-directly/38295/2?u=mikeinnes

**Comment by ChrisRackauckas** [comment]
Seems like it might be related, but in the Discourse post you link, both the global and the local are used, while here it's either the global or the local are used, while the global and the local just happen to be the same array. I get how in the Discourse post version how you could get confusion of the perturbations, I don't get how it could show up in this either/or scenario.

**Comment by ChrisRackauckas** [comment]
We are even directly checking if it's the same array in the third example: https://github.com/SciML/DiffEqBase.jl/blob/master/src/solve.jl#L68

**Comment by ChrisRackauckas** [comment]
Indeed making the MWE branching works, so I don't think that's quite it:

```julia
x = 1.5
f(y) = x == 2 ? x : y
gradient(f, x) #1.0
```

**Comment by ChrisRackauckas** [comment]
Maybe @MikeInnes could help out as well

**Comment by MikeKlocCZ** [comment]
I have now encountered the gradient doubling problem even in a very trivial case with only a single layer NN.
`
using Flux

model=Dense(1,1,identity)
model.W[1]=2.0f0
model.b[1]=1.0f0
p1,re=Flux.destructure(model)
u0=[2.0f0]
### with a simple NN
function simple(p1)
   p2=re(p1)(u0)
   sum(p2-u0)
end
### without the NN
function simple_no_net(p1)
   p2=p1[1].*u0.+p1[2]
   sum(p2-u0)
end

θ=Flux.params(p1)
gs1 = gradient(θ) do
   simple(p1)
end
println("grads:", gs1[p1] ) #Float32[4.0, 2.0] ...#doubled

using ForwardDiff
ForwardDiff.gradient(simple,p1) ##Float32[2.0, 1.0] ...#OK

gs2 = gradient(θ) do
   simple_no_net(p1)
end
println("grads no NN:",gs2[p1]) #Float32[2.0, 1.0] ...#OK`

So it looks like something happens when reconstruct the network with `re`.

**Comment by ChrisRackauckas** [comment]
Looks like it's the same thing: it's an issue to have the variable global and local, even if it's just choosing one or the other and they are the same.

**Comment by ChrisRackauckas** [comment]
That's a good MWE without DiffEq though. Would you mind adding it to Zygote.jl proper? That might push the issue a bit more.

**Comment by MikeKlocCZ** [comment]
Sure, I will open an issue directly under Zygote.jl as the thing is apparently not linked to DiffEqFlux package.  

So I understand that the problem stems from a confusion between local and global nature of the parameters. So in this simple example the problem is that the reconstruction of the network needs to take the parameters as global? Is that right?

**Comment by ChrisRackauckas** [comment]
>So I understand that the problem stems from a confusion between local and global nature of the parameters. So in this simple example the problem is that the reconstruction of the network needs to take the parameters as global? Is that right?

`p` local and global are the same array, and when it's backpropogating it's adding the perturbation to "all arrays involved", which is both the local array and the global array, but since they are the same, it sees the gradient as two times the real perturbation.

**Comment by MikeInnes** [comment]
Thanks for the sensible test case. This is not a local/global confusion issue because `p1` is only accessed as a formal argument in the body of `simple`, not as both a formal argument and a global. It's just a zygote bug which is fixed in https://github.com/FluxML/Zygote.jl/pull/688.

**Comment by ChrisRackauckas** [comment]
Ahh, that makes sense. Thanks for the quick fix. @MikeKlocCZ could you quickly test your original case with that branch just to make sure it covers it all? If it does, we can close this when that PR merges.

**Comment by MikeKlocCZ** [comment]
@ChrisRackauckas Yeah, all the gradients are now computed correctly for all the examples! However, I also tried some more 'extensive' tests like hooking a function on the gradients and it gives me the following error 
```julia
gs_flip = gradient(θ) do
          simple(Zygote.hook(-,p1))
       end
ERROR: MethodError: no method matching -(::Nothing)
Closest candidates are:
  -(::Bool, ::Complex{Bool}) at complex.jl:288
  -(::Bool, ::Bool) at bool.jl:97
  -(::Bool) at bool.jl:94
```
This looks like related to the new fix by @MikeInnes

**Comment by MikeInnes** [comment]
It is related but technically the right behaviour; the gradient of the value `p1` has already been 'used up' (accumulated into `Grads`) by the time the hook is hit, so the gradient of the local variable `p1` is `nothing`. To avoid this you can make a copy of `p1` and `hook` that, before passing it to `simple`; of course you can also just use the explicit form, which is less prone to this kind of subtlety.

**Comment by MikeKlocCZ** [comment]
I see, by making a copy it works perfectly!  It's however not very intuitive (at least for me). Maybe it could be worth adding some notes on this to the documentation of the hook function. I am still using Zygote.hook() to clip gradients, for example. Anyway, thank you both for your feedback and help!

**Comment by ChrisRackauckas** [comment]
Looks like the actionable part https://github.com/FluxML/Zygote.jl/pull/688 merged so we're good to go.
