### ISSUE TITLE
Interpreting the output of the adjoint_sensitivities function

### ISSUE THREAD

**Issue by mjohnson541** [SciML/DiffEqSensitivity.jl#282]
I'm trying to use adjoint_sensitivities to calculate the derivative of a component of the solution with respect to a set of parameters. However, this seemed to disagree with the sensitivities i was calculating using forward sensitivity analysis. I scaled down to the simple example below where I knew the analytic solution and everything I tested agreed except for adjoint:  

```
using DifferentialEquations
using DiffEqSensitivity
using Sundials
using QuadGK
using ForwardDiff

p = [2.0]
u0 = [2.0]
function f(du,u,p,t)
    du[1] = -u[1]*p[1]
end

prob = ODEProblem(f,u0,(0.0,1.0),p)
sol = solve(prob,CVODE_BDF(),abstol=1e-10,reltol=1e-10);

-1.0*u0[1]*exp(-p[1]*1.0) #analytic -0.2706705664732254

g(u,p,t) = -u[1]*p[1] 

function G(p)
  tmp_prob = remake(prob,p=p)
  sol = solve(tmp_prob,Vern9(),abstol=1e-10,reltol=1e-10)
  h(t) = g(sol(t),p,t)
  res,err = quadgk(h,0.0,1.0;atol=1e-10,rtol=1e-10)
  res 
end

res2 = ForwardDiff.gradient(G,[2.0]) #brute force auto diff -0.2706705664733001

sensprob = ODELocalSensitivityProblem(f,u0,(0.0,1.0),p)
solsens = solve(sensprob,Vern9(),abstol=1e-10,reltol=1e-10);

solsens.u[end][2] #forward sensitivities -0.27067056647320015

du0,dp = adjoint_sensitivities(sol,Vern9(),g,nothing;abstol=1e-10,reltol=1e-10)
dp # adjoint 0.5939941500266327
```

I assume I'm interfacing incorrectly with the function, or misunderstanding the output but I'm not sure how. The documentation is very good at explaining what's going on, but I'm not sure if I really understand what the outputs du0 and dp are exactly after reading it.

**Comment by ChrisRackauckas** [comment]
Seems like it's this issue popping up again. https://github.com/SciML/DiffEqSensitivity.jl/issues/92

@YingboMa when you did the new derivations of the adjoint, did you see where dg/dp should go?

**Comment by ChrisRackauckas** [comment]
This was also solved by https://github.com/SciML/DiffEqSensitivity.jl/issues/92

**Comment by mjohnson541** [comment]
Running the code above on v6.21.1 still gives me the same results as before.

**Comment by ChrisRackauckas** [comment]
@YingboMa would you know why this wasn't covered?

**Comment by YingboMa** [comment]
Currently, we need the user to pass in `dg/du` and `dg/dp` terms, so
```julia
julia> dgdu(out, y, p, t) = ForwardDiff.gradient!(out, y -> g(y, p, t), y)
dgdu (generic function with 1 method)

julia> dgdp(out, y, p, t) = ForwardDiff.gradient!(out, p -> g(y, p, t), p)
dgdp (generic function with 1 method)

julia> du0,dp = adjoint_sensitivities(sol,Vern9(),g,nothing,(dgdu,dgdp);abstol=1e-10,reltol=1e-10)
([-0.8646647167633873], [-0.2706705665561804])
```
gives the expected output.

**Comment by ChrisRackauckas** [comment]
Let's get a documentation update?

**Comment by ChrisRackauckas** [comment]
docs updated and we're good to go. Thanks for pointing this out.
