### ISSUE TITLE
Support state-dependent continuous callbacks with adjoints

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqSensitivity.jl#374]
https://github.com/SciML/DiffEqSensitivity.jl/pull/350 did the discrete callbacks. It shouldn't be much more to similarly wrap the continuous callbacks.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqSensitivity.jl/issues/197 should get tested and closed when this is completed.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqSensitivity.jl/pull/381 found that it's all good except when `u`-dependent, so it requires an extra term.

**Comment by ChrisRackauckas** [comment]
@frankschae was this handled?

**Comment by frankschae** [comment]
No, it's not done yet. Michael and Stefano pointed me to this paper: https://arxiv.org/abs/2011.03902 but I think the derivation lacks the details about which limit one has to take (I still try to figure that out but generally it looks like that will potentially solve the issue). Maybe @YingboMa could also have a look what term from the chain rule we should add to our code.
