### ISSUE TITLE
TypeError for ODELocalSensitivityProblem with Kvaerno5 as solver

### ISSUE THREAD

**Issue by yilinyang1** [SciML/DiffEqSensitivity.jl#402]
I tried to use ODELocalSensitivityProblem with Kvaerno5 as the stiff system solver. But it reports TypeError: "in typeassert, expected Float64, got a value of type ForwardDiff.Dual{Nothing, Float64, 8}".

`
function f(du, u, p, t)
    du[1] = dx = p[1] * u[1] - p[2] * u[1] * u[2]
    du[2] = dy = -p[3] * u[2] + u[1] * u[2]
end

p = [1.5,1.0,3.0]
prob = ODELocalSensitivityProblem(f,[1.0;1.0],(0.0,10.0),p)
sol = solve(prob,Kvaerno5(),saveat=LinRange(0.0, 10.0, 11))
`
However, this code works for DP8 as the solver

**Comment by ChrisRackauckas** [comment]
This seems like a problem similar to https://github.com/SciML/DiffEqSensitivity.jl/issues/393 . Workaround is just `sol = solve(prob,Kvaerno5(autodiff=false),saveat=LinRange(0.0, 10.0, 11))`

**Comment by yilinyang1** [comment]
Thanks! I saw in another issue #398 that MTK could be a possible solution for that issue. Do you think MTK could solve this issue also?

**Comment by ChrisRackauckas** [comment]
It would if you generate the code because there wouldn't be a gradient clash.

**Comment by yilinyang1** [comment]
I see, thanks!

**Comment by JianghuiDu** [comment]
Can this problem be solved without MTK? Or are we just waiting for new AD tools?

**Comment by ChrisRackauckas** [comment]
It would be fairly hard with the current AD tools. New Diffractor is the solution here.

**Comment by JianghuiDu** [comment]
When is the new AD tool expected? I've seen some whispers online...

**Comment by ChrisRackauckas** [comment]
🤷

**Comment by JianghuiDu** [comment]
😂
