### ISSUE TITLE
Pre-compilation failing, UndefVarError: SciMLBase not defined

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [SciML/DiffEqSensitivity.jl#410]
When pre-compiling both the 6.44.1 version and the current master I get the following error: 

```Julia 
[ Info: Precompiling DiffEqSensitivity [41bf760c-e81c-5289-8e54-58b1f1f8abe2]
ERROR: LoadError: LoadError: UndefVarError: SciMLBase not defined
Stacktrace:
 [1] top-level scope at /xxx/.julia/packages/DiffEqSensitivity/LDOtY/src/forward_sensitivity.jl:278
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include at ./Base.jl:368 [inlined]
 [4] include(::String) at /xxx/.julia/packages/DiffEqSensitivity/LDOtY/src/DiffEqSensitivity.jl:1
 [5] top-level scope at /xxx/.julia/packages/DiffEqSensitivity/LDOtY/src/DiffEqSensitivity.jl:21
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] top-level scope at none:2
 [9] eval at ./boot.jl:331 [inlined]
 [10] eval(::Expr) at ./client.jl:467
 [11] top-level scope at ./none:3
``` 

I had a brief glance at the code and `SciMLBase` does not seem to be imported anywhere, so this is likely the issue.

**Comment by ChrisRackauckas** [comment]
Julia v1.6?

**Comment by maximilian-gelbrecht** [comment]
v1.5.3

**Comment by ChrisRackauckas** [comment]
What version of SciMLBase do you have?

What you're right it's not explicitly imported, it is implicitly through the `@reexport` of StochasticDiffEq. We should add a `using SciMLBase` there to make it explicit, but that would just be for clarity.

**Comment by maximilian-gelbrecht** [comment]
SciMLBase is v1.13.0

**Comment by ChrisRackauckas** [comment]
This is odd. Did you just update packages? Try just restarting the REPL and see if it reoccurs?

**Comment by maximilian-gelbrecht** [comment]
First of all, thank you for your super quick responses. 

Restarting the REPL didn't help, I also updated all other packages and while doing so I updated Reexport from 0.2.0 -> 1.0.0. Also didn't do anything. It's really a bit strange because on my local laptop (Julia v.1.5.4, using DiffEqSensitivity.jl implicitly through DiffEqFlux v1.34.1) it does compile.

**Comment by ChrisRackauckas** [comment]
DiffEqBase version, or StochasticDiffEq version? Yeah I'm a bit confused: it is just a versioning thing though.

**Comment by maximilian-gelbrecht** [comment]
I have DifferentialEquations v6.16.0 and DiffEqFlux v1.33.0 on the non-working installation. DiffEqBase and StochasticDiffEq only implicitly trough those

**Comment by maximilian-gelbrecht** [comment]
Okay, I removed another package that prohibited me from updating the DiffEq packages further (to DiffEqBase v6.60.0) and now  DiffEqSensitivity.jl does compile. 
Not always easy to manage all these cross-dependencies ...

**Comment by ChrisRackauckas** [comment]
Yeah, we keep bumping minimums to hope it gets easier... we need the differentiation space to stabilize a bit.
