### ISSUE TITLE
ODEForwardSensitivityProblem always autojacvec

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqSensitivity.jl#450]
```jl
using DiffEqSensitivity
using OrdinaryDiffEq

function f(du,u,p,t)
du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
du[2] = dy = -p[3]*u[2] + u[1]*u[2]
end
p = [1.5,1.0,3.0]

prob = ODEForwardSensitivityProblem(f,[1.0;1.0],(0.0,10.0),p, sensealg = ForwardSensitivity(autojacvec=false))
prob.f.isautojacvec #true
```

As far as I can tell jacvec is always used no matter what option is passed, also when autodiff=false?
I do not think this issue exists when using the high level interface.

Why is jacvec the standard option? This calculates directional derivatives, which has to be done n_p times. With n_p the number of parameters. So are you gaining much compared to calculating the full jacobian? In any case the n_p directional derivatives could be calculated all together in a single function call to the dynamic system (or at least chunked) by seeding more than a single partial.

**Comment by ArnoStrouwen** [comment]
I figured out the difference:
In the high level interface `sensealg` is a keyword argument but not in the lower level interface.

**Comment by ChrisRackauckas** [comment]
>Why is jacvec the standard option? This calculates directional derivatives, which has to be done n_p times. With n_p the number of parameters.

No, this only takes 1 directional derivative, regardless of the Jacobian. See https://arxiv.org/abs/1812.01892 which mentions how.

**Comment by ChrisRackauckas** [comment]
>In the high level interface sensealg is a keyword argument but not in the lower level interface.

Interesting. We should make the lower level interface match the sensealg way.

**Comment by ArnoStrouwen** [comment]
> 
> 
> > Why is jacvec the standard option? This calculates directional derivatives, which has to be done n_p times. With n_p the number of parameters.
> 
> No, this only takes 1 directional derivative, regardless of the Jacobian. See https://arxiv.org/abs/1812.01892 which mentions how.

To me it looks like you calculate a single directional derivative n_p times.
https://github.com/SciML/DiffEqSensitivity.jl/blob/02333f0cc3186b06ee521323c5be45a0ea5f2c2d/src/forward_sensitivity.jl#L93-L99
In the paper you also only give the formula for the sensitivity towards a single parameter. What I'm imagining is doing this for all parameters at once (or if there are too many parameters you can chunk it).

I think it should be equivalent to taking the jacobian towards w1 ... wp of f(u+w1 direction1 + ... + wp directionp) evaluated at zero for the w. 

This might be achieved by clever seeding with more than a single partial? e.g. if you need to calculate the derivatives in the directions (1,2) and (-1,3) you seed as [(u1, 1, -1), (u2,2,3)].

**Comment by ChrisRackauckas** [comment]
No, see the discussion on equation 4. `jacobianvec!` is always just a single differentiation direction.

**Comment by ArnoStrouwen** [comment]
I still think you do n_p jacobian free jacobian vector products, instead of doing a "jacobian free jacobian matrix product"
(I don't know the correct terminology for this).
I made a quick prototype, which gives a significant performance increase, though I had to resort to dispatching on the value of n_p because of how partials work in ForwardDiff.

```jl
using OrdinaryDiffEq
using DiffEqSensitivity
using ForwardDiff
using Plots, BenchmarkTools

function f(du,u,p,t)
    du[1] = p[1]*u[1] - p[2]*u[1]*u[2]
    du[2] = -p[3]*u[2] + p[4]*u[1]*u[2]
end
u0 = [1.0;1.0]
p = [1.5,1.0,3.0,1.0]
prob = ODEForwardSensitivityProblem(f,u0,(0.0,10.0),p,ForwardSensitivity())
sol = solve(prob,Tsit5())
@btime solve(prob,Tsit5()) # 116.009 μs (488 allocations: 78.42 KiB)

prob = ODEForwardSensitivityProblem(f,u0,(0.0,10.0),p,ForwardSensitivity(autojacvec=false))
const n_u = prob.f.numindvar
const n_p = prob.f.numparams
const val_n_p = Val(n_p)
const u_ext_helper = prob.u0
const du_ext_helper  = similar(u_ext_helper)
const u_helper = @view u_ext_helper[1:n_u]
const du_helper = @view du_ext_helper[1:n_u]
const du_dp_helper = reshape(@view(u_ext_helper[n_u+1:end]),n_u,n_p)
const d_du_dp_helper = reshape(@view(du_ext_helper[n_u+1:end]),n_u,n_p)
const pf = prob.f.pf
const uf = prob.f.uf
const jac_config_p = ForwardDiff.JacobianConfig(pf, du_helper, prob.p)
const cache_duals_in = ForwardDiff.Dual{Nothing}.(u_helper,[ForwardDiff.Partials(tuple(row...)) for row in eachrow(du_dp_helper)])
const cache_duals_out = similar(cache_duals_in)
const caches = (n_u=n_u,n_p = n_p,val_n_p=val_n_p,pf = pf,uf = uf,jac_config_p=jac_config_p,cache_duals_in = cache_duals_in,cache_duals_out = cache_duals_out )

function csa_vec_mat(du_ext,u_ext,p,t,caches)
    n_u = caches.n_u
    n_p = caches.n_p
    val_n_p = caches.val_n_p
    pf = caches.pf
    uf = caches.uf
    jac_config_p= caches.jac_config_p
    cache_duals_in = caches.cache_duals_in
    cache_duals_out = caches.cache_duals_out 

    u = @view u_ext[1:n_u]
    du = @view du_ext[1:n_u]
    du_dp = reshape(@view(u_ext[n_u+1:end]),n_u,n_p)
    d_du_dp = reshape(@view(du_ext[n_u+1:end]),n_u,n_p)
    pf.t = t
    pf.u .= u
    ForwardDiff.jacobian!(d_du_dp, pf, du, p,jac_config_p) 
    uf.t = t
    for i in 1:length(cache_duals_in)
        cache_duals_in[i] = ForwardDiff.Dual{Nothing}(u[i],ForwardDiff.Partials(ntuple(k -> du_dp[i,k], val_n_p)))
    end
    uf(cache_duals_out,cache_duals_in)
    for  j in 1:size(d_du_dp,2)
        for i in 1:size(d_du_dp,1)
            d_du_dp[i,j] += cache_duals_out[i].partials[j]
        end
    end
    return nothing
end
csa_vec_mat(du_ext,u_ext,p,t) = csa_vec_mat(du_ext,u_ext,p,t,caches)
prob2 = ODEProblem(csa_vec_mat,prob.u0,(0.0,10.0),p)
sol = solve(prob2,Tsit5())
@btime solve(prob2,Tsit5()) #  68.056 μs (487 allocations: 76.91 KiB)
plot(sol)
```

**Comment by ChrisRackauckas** [comment]
I see what you're doing now. Most of that performance issue seems to actually have been due to broadcast performance issues. The package version now is at: `73.500 μs (485 allocations: 78.20 KiB)` so fairly close.

If you want to keep going on https://github.com/SciML/DiffEqSensitivity.jl/pull/453 and add some chunking, that would be great.

**Comment by ChrisRackauckas** [comment]
Try the new master.

**Comment by ArnoStrouwen** [comment]
on v6.57.0 116.009 μs (488 allocations: 78.42 KiB) 
on new master 101.898 μs (489 allocations: 78.48 KiB)
my prototype 67.442 μs (488 allocations: 76.97 KiB)

So there is still quite a bit of performance on the table.

**Comment by ChrisRackauckas** [comment]
Did you try the master with https://github.com/SciML/DiffEqSensitivity.jl/pull/459 ?

**Comment by ArnoStrouwen** [comment]
I think so, since it has the v6.58.0 tag now.
I wonder how this pr changes table 1 of your sensitivity benchmarking arxiv paper.
```
(tester) pkg> status
      Status `~/Koofr/tester/Project.toml`
  [9fdde737] DiffEqOperators v4.30.0
  [41bf760c] DiffEqSensitivity v6.58.0 `https://github.com/SciML/DiffEqSensitivity.jl.git#master`
  [f6369f11] ForwardDiff v0.10.19
  [961ee093] ModelingToolkit v5.26.0
  [429524aa] Optim v1.4.1
  [1dea7af3] OrdinaryDiffEq v5.60.2
  [37e2e3b7] ReverseDiff v1.9.0
  [c3572dad] Sundials v4.5.3
  [0c5d862f] Symbolics v1.4.2
  [e88e6eb3] Zygote v0.6.17
```

**Comment by ChrisRackauckas** [comment]
Weird, since you may have a different timing, but it shouldn't be different in allocations?

```julia
using OrdinaryDiffEq
using DiffEqSensitivity
using ForwardDiff
using Plots, BenchmarkTools

function f(du,u,p,t)
    du[1] = p[1]*u[1] - p[2]*u[1]*u[2]
    du[2] = -p[3]*u[2] + p[4]*u[1]*u[2]
end
u0 = [1.0;1.0]
p = [1.5,1.0,3.0,1.0]
prob = ODEForwardSensitivityProblem(f,u0,(0.0,10.0),p,ForwardSensitivity())
sol = solve(prob,Tsit5())
@btime solve(prob,Tsit5()) # 72.700 μs (488 allocations: 70.31 KiB)
```

is my current state.

**Comment by ChrisRackauckas** [comment]
The extra allocation would come from `@.` not being efficient there.

**Comment by ChrisRackauckas** [comment]
Would you mind doing a PR to add a flag for your chunked version? I think it would be good to have in the library in an optimized way so that we can do more studies with it.

**Comment by ArnoStrouwen** [comment]
I don't think it would be too hard to make a version that construct duals with all the partials at once. This compared to the current version that does one partial at a time. And I shall do that next weekend.

However, what is more difficult is if there are 100 parameters. What you would ideally do is a medium number of partials (say 13 as that is the ForwardDiff standard I think), 7 times and then the 9 remaining partials. That would be more difficult to get right, as it complicates all the caches that have to be passed.

**Comment by ChrisRackauckas** [comment]
Yes, agreed. For now we can do the one without chunking, since chunking should just change compile times.

**Comment by ArnoStrouwen** [comment]
Implemented some time ago in https://github.com/SciML/DiffEqSensitivity.jl/pull/470 .
I think chucked mode would have more advantages than compile time.
Are there also not memory considerations?

**Comment by ChrisRackauckas** [comment]
Yeah, there's a memory consideration there too.
