### ISSUE TITLE
original jac ForwardSensitivity

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqSensitivity.jl#472]
I do not think this line ever evaluates to true.

https://github.com/SciML/DiffEqSensitivity.jl/blob/b2d33c3e62fd8571e0d0028360f8534352c2af59/src/forward_sensitivity.jl#L75
There is no field original_jac, only the misspelled orginal
https://github.com/SciML/DiffEqSensitivity.jl/blob/b2d33c3e62fd8571e0d0028360f8534352c2af59/src/forward_sensitivity.jl#L5
Which would mean all the benchmarks with analytical jacobians are actually using finite differences?

**Comment by ChrisRackauckas** [comment]
oh that's an issue. Quick PR? @YingboMa ?

**Comment by ArnoStrouwen** [comment]
Fixed by #477 .
Benchmarks for the arxiv report about sensitivity analysis might be influenced by this.
But I can't find a public version of that code.
