### ISSUE TITLE
MethodError: no method matching Enzyme.Duplicated(::SciMLBase.NullParameters, ::Vector{Float64})

### ISSUE THREAD

**Issue by rekabrnalla** [SciML/DiffEqSensitivity.jl#514]
Updated to latest today and got this error.
It appears that in _vecjacobian! derivative_wrappers.jl, line 496, the p argument is being set to SciMLBase.NullParameters() and Enzyme.Deuplicated doesn't know what to do with that.

My example used to work fine a months or so ago.  I didn't do a good job of tracking the manifest from back then.

I don't usually report stuff to github directly, so I'm probably not following any of the rules.
If you need to dump this issue, that is fine, I thought someone should know if it was an easy fix or not.

My not complete code snips are:
`function predict_nnet(θ,percentOfFlight;data=ode_data,problem=prob)
	# Get an input sequence
	input=grabNetworkInput(percentOfFlight;data=data)
	# Push through network
	x=ann(θ)(input)
	# Exercise Solver with output as initial conditions
	prob0=remake(problem,u0=x,saveat=0.1)
	Array(solve(prob0))
end`

`function loss_n_ode(θ)
	value=0.0
	# Grade against the set
	for POF in inputSet
		tempAns = vec(predict_nnet(θ,POF)[:,1:inputSize])  # Only return the same size as the window
		truthTrace=grabNetworkInput(POF)  # Get the input that network is trying to guess parameters for
		value = value + sum(abs2,truthTrace .- tempAns)
	end
	value
end`

res=DiffEqFlux.sciml_train(loss_n_ode, θ,  cb = (p,l)->cb(p,l,anim), allow_f_increases=true)

[error_stack.txt](https://github.com/SciML/DiffEqSensitivity.jl/files/7688886/error_stack.txt)

**Comment by rekabrnalla** [comment]
Forgot Status:
`[537997a7] AbstractPlotting v0.18.3
  [35d6a980] ColorSchemes v3.15.0
  [aae7a2af] DiffEqFlux v1.44.0
  [41bf760c] DiffEqSensitivity v6.62.1
  [0c46a032] DifferentialEquations v6.20.0
  [587475ba] Flux v0.12.8
  [f6369f11] ForwardDiff v0.10.23
  [e9467ef8] GLMakie v0.4.5
  [28b8d3ca] GR v0.57.5
  [0337cf30] GRUtils v0.6.2
  [824d6782] JSServe v1.2.3
  [23fbe1c1] Latexify v0.15.9
  [89398ba2] LocalRegistry v0.5.0
  [10e44e05] MATLAB v0.8.2
  [ee78f7c6] Makie v0.15.1
  [961ee093] ModelingToolkit v7.1.3
  [429524aa] Optim v1.5.0
  [1dea7af3] OrdinaryDiffEq v5.69.0
  [91a5bcdd] Plots v1.22.5
  [c3e4b0f8] Pluto v0.17.3
  [7f904dfe] PlutoUI v0.7.21
  [f27b6e38] Polynomials v2.0.17
  [731186ca] RecursiveArrayTools v2.20.0
  [37e2e3b7] ReverseDiff v1.11.0
  [295af30f] Revise v3.2.0
  [00bb0486] StandardAerospace v0.3.1
  [d1185830] SymbolicUtils v0.18.1
  [0c5d862f] Symbolics v4.1.1
  [a2db99b7] TextAnalysis v0.7.3
  [f269a46b] TimeZones v1.7.0
  [276b4fcb] WGLMakie v0.4.5
  [e88e6eb3] Zygote v0.6.32
  [7e2434f1] xyzVector v0.4.1 `C:\Users\bakerar\Documents\2020\Julia\development\xyzVector`
  [37e2e46d] LinearAlgebra
  [8dfed614] Test`


Julia version: 1.6.3

**Comment by ChrisRackauckas** [comment]
Looks like I can reproduce it, and trying to fix it leads to an Enzyme segfault: https://github.com/SciML/DiffEqSensitivity.jl/pull/515

https://github.com/SciML/DiffEqSensitivity.jl/pull/516 will fix the defaults for now.

**Comment by ChrisRackauckas** [comment]
Fixed!
