### ISSUE TITLE
Sensitivity benchmark paper, table III

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqSensitivity.jl#571]
In this paper about sensitivity benchmarking: https://arxiv.org/pdf/1812.01892.pdf ; Table III, row 3 and 4 being almost identical seems unlikely to me. Maybe the same sensitivity algorithm was ran twice by accident?

**Comment by ChrisRackauckas** [comment]
Feel free to take a look at the script: https://github.com/PumasAI/sensitivity_analysis_paper/blob/master/script/bruss_scaling.jl. Open an issue there if you find anything.
