### ISSUE TITLE
Precompilation warning: method definition setindex() overwritten

### ISSUE THREAD

**Issue by vleon1234** [SciML/DiffEqSensitivity.jl#603]
Since v6.76.0, I get this warning message at each precompilation. The package still precompiles and works as expected.

[ Info: Precompiling DiffEqSensitivity [41bf760c-e81c-5289-8e54-58b1f1f8abe2]
WARNING: Method definition setindex(AbstractArray{T, 2} where T, Any, Int64, Int64) in module ArrayInterface at C:\Users\vleon\.julia\packages\ArrayInterface\TCj9U\src\ArrayInterface.jl:163 overwritten in module 
ArrayInterfaceCore at C:\Users\vleon\.julia\packages\ArrayInterfaceCore\edbd7\src\ArrayInterfaceCore.jl:115.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition setindex(AbstractArray{T, 1} where T, Any, Int64) in module ArrayInterface at C:\Users\vleon\.julia\packages\ArrayInterface\TCj9U\src\ArrayInterface.jl:158 overwritten in module ArrayInterfaceCore at C:\Users\vleon\.julia\packages\ArrayInterfaceCore\edbd7\src\ArrayInterfaceCore.jl:110.     
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition setindex(AbstractArray{T, N} where N where T, Any, Any...) in module ArrayInterface at C:\Users\vleon\.julia\packages\ArrayInterface\TCj9U\src\ArrayInterface.jl:152 overwritten in module ArrayInterfaceCore at C:\Users\vleon\.julia\packages\ArrayInterfaceCore\edbd7\src\ArrayInterfaceCore.jl:104.
  ** incremental compilation may be fatally broken for this module **

**Comment by ChrisRackauckas** [comment]
Try `]add ArrayInterface@6`

**Comment by vleon1234** [comment]
This worked thanks!
