### ISSUE TITLE
Still problems with the docu

### ISSUE THREAD

**Issue by MaAl13** [SciML/DiffEqSensitivity.jl#641]

**Comment by MaAl13** [comment]
Hi Chris, 
i assumed that it was the same code that i posted in the problem, but indeed by changing from cb to callback (as it is in the docu now) it is running! Maybe just for the docu, it is missing:
using DiffEqSensitivity 
using Zygote
otherwise it throws an error!

Thank you so much for the support!!!

**Comment by ChrisRackauckas** [comment]
>  Maybe just for the docu, it is missing:

Thanks for noticing that. Interesting that the doctests didn't catch that. I'll have to find out how to make that caught by the tests.

**Comment by FabiJa** [comment]
> > Maybe just for the docu, it is missing:
> 
> Thanks for noticing that. Interesting that the doctests didn't catch that. I'll have to find out how to make that caught by the tests.

For me it seems to work without the additional import, but I have:
[41bf760c] DiffEqSensitivity v6.79.0 `https://github.com/SciML/DiffEqSensitivity.jl.git#master`
[7f7a1694] Optimization v3.6.1 `https://github.com/SciML/Optimization.jl.git#master`
