### ISSUE TITLE
Stable documentation links return 404

### ISSUE THREAD

**Issue by andreasnoack** [SciML/DiffEqSensitivity.jl#642]
It looks like only the dev docs are being deployed.

**Comment by ChrisRackauckas** [comment]
Yeah there's a few repos doing that, and I'm not sure why. Maybe someone like @staticfloat knows what's going on. LinearSolve.jl, NonlinearSolve.jl, etc. all have the same issue.

**Comment by staticfloat** [comment]
I don't know why, I'm not that experienced with Documenter.  @mortenpi would know better, I think.

**Comment by mortenpi** [comment]
It looks like the `Documentation` workflow is not running for tags.. which is likely because TagBot doesn't have a deploy key to work with. Have you set up the `DOCUMENTER_KEY` variable here?

**Comment by ChrisRackauckas** [comment]
Setup the keys, we should be good now.
