### ISSUE TITLE
tutorials are not following the SciML style

### ISSUE THREAD

**Issue by MilkshakeForReal** [SciML/DiffEqSensitivity.jl#658]
The indentation [rule](https://github.com/SciML/SciMLStyle#functions) is not strcitly followed in several places
![image](https://user-images.githubusercontent.com/38997672/175134578-2b4e7140-5b55-405a-bbcf-098242aecfda.png)

**Comment by ChrisRackauckas** [comment]
I know. It's part of https://github.com/SciML/SciMLDocs/issues/24 to have someone go and run the formatter on all repos. Right now I'm more concerned about getting them all correct, but if someone wants to run the formatter here, it'll find a lot.

**Comment by MilkshakeForReal** [comment]
Yeah no big deal.
