### ISSUE TITLE
Drop dependency on GLM

### ISSUE THREAD

**Issue by andreasnoack** [SciML/DiffEqSensitivity.jl#99]
It's only used for linear regression, e.g. https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/blob/a565c73581d88b29b84eee6b5ee0feb0eb1faa04/src/regression_sensitivity.jl#L113 and, in this application, it would be simpler just to use `\`. A nice side effect would be that you avoid `Meta.parse` and `eval`.

**Comment by Vaibhavdixit02** [comment]
Yes this is a good suggestion. I'll take it up at some point in the near future, we need a lot of the `regression_sensitivity` to be re-written.
